### ISSUE TITLE
LRU cache

### ISSUE THREAD

**Issue by heyman** [normanrz/elevation-service#1]
First of all, really nice work :)!

How did you choose the size of the LRU cache? Perhaps it would be nice to be able to configure it in an environment variable?

Also, I believe that the default gunicorn worker model uses processes, which would make the LRU cache not shared between gunicorn workers if I'm not mistaken?

**Comment by normanrz** [comment]
Yeah, I just picked a size that worked well for me :D I am happy to take PRs on that.

I don't know much about gunicorn. So any pointers how to make the cache sharing possible are appreciated.

**Comment by heyman** [comment]
> Yeah, I just picked a size that worked well for me :D I am happy to take PRs on that.

I see! I'm going on vacation for a week, but I might make a PR when I'm back.

> So any pointers how to make the cache sharing possible are appreciated.

I think that changing Gunicorn's worker model to asynchronous (through Gevent), or threads, would make the cache sharing work. It would also fix so that an API request won't hog a whole process while a tile is being downloaded from S3. One caveat though is that the server wouldn't be able to achieve any CPU parallelism.

**Comment by normanrz** [comment]
The new implementation has a configurable LRU cache size. However, it only caches in-memory not on -disk.
